# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalEntry',
            fields=[
                ('facility_number', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('zip_code', models.CharField(max_length=10)),
                ('bed_lic', models.IntegerField()),
                ('bed_avl', models.IntegerField()),
            ],
        ),
    ]
